# Generated by Django 5.1.6 on 2026-03-11 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone SVG', max_length=50, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'conhecimento_categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('conteudo', models.TextField(help_text='Suporta Markdown', verbose_name='conteúdo')),
                ('resumo', models.CharField(blank=True, max_length=500, verbose_name='resumo')),
                ('visibilidade', models.CharField(choices=[('todos', 'Todos (consultor + seller)'), ('consultores', 'Apenas Consultores'), ('gestores', 'Apenas Gestores')], default='todos', max_length=20, verbose_name='visibilidade')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='visualizações')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='conhecimento.categoriaconhecimento')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'db_table': 'conhecimento_artigos',
                'ordering': ['-destaque', '-created_at'],
            },
        ),
    ]
