# Generated by Django 5.1.6 on 2026-03-11 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('mes', models.PositiveIntegerField(verbose_name='mês')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('arquivo', models.FileField(blank=True, upload_to='relatorios/%Y/%m/', verbose_name='PDF')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados do relatório')),
                ('enviado', models.BooleanField(default=False, verbose_name='enviado')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_mensais', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
                'db_table': 'relatorios_mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cliente', 'mes', 'ano')},
            },
        ),
    ]
