# Generated by Django 5.1.6 on 2026-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='slug')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'accounts_modulo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='modulos',
            field=models.ManyToManyField(blank=True, help_text='Módulos que este usuário pode acessar. Gestores têm acesso total.', to='accounts.modulo', verbose_name='módulos permitidos'),
        ),
    ]
