# Generated by Django 5.1.6 on 2026-03-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('consultor', 'Consultor'), ('seller', 'Seller'), ('funcionario', 'Funcionário')], default='seller', max_length=20, verbose_name='papel'),
        ),
    ]
