# Generated by Django 5.1.6 on 2026-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('consultor', 'Consultor'), ('seller', 'Seller'), ('funcionario', 'Funcionário'), ('comercial', 'Comercial')], default='seller', max_length=20, verbose_name='papel'),
        ),
    ]
