# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('especialidade', models.CharField(blank=True, max_length=200, verbose_name='especialidade')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('max_clientes', models.PositiveIntegerField(default=10, verbose_name='máx. clientes')),
                ('usuario', models.OneToOneField(limit_choices_to={'role': 'consultor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'db_table': 'consultores',
            },
        ),
    ]
