# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone Flowbite/Heroicons', max_length=50, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Checklist',
                'verbose_name_plural': 'Categorias de Checklist',
                'db_table': 'checklist_categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='ícone')),
                ('target_audience', models.CharField(choices=[('consultant', 'Consultor'), ('client', 'Cliente')], default='consultant', max_length=20, verbose_name='público-alvo')),
                ('tipo', models.CharField(choices=[('onboarding', 'Onboarding'), ('recorrente', 'Recorrente'), ('avulso', 'Avulso')], default='avulso', max_length=20, verbose_name='tipo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklist',
                'db_table': 'checklist_templates',
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('score', models.PositiveIntegerField(default=0, help_text='Percentual 0-100', verbose_name='score')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='clientes.cliente')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_executados', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Execução de Checklist',
                'verbose_name_plural': 'Execuções de Checklist',
                'db_table': 'checklist_execucoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.CharField(max_length=500, verbose_name='descrição')),
                ('instrucoes', models.TextField(blank=True, help_text='Instruções detalhadas para o item', verbose_name='instruções')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='exige evidência')),
                ('requires_note', models.BooleanField(default=False, verbose_name='exige observação')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_itens', to='checklists.checklistcategory', verbose_name='categoria')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item do Template',
                'verbose_name_plural': 'Itens do Template',
                'db_table': 'checklist_template_itens',
                'ordering': ['category__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('conforming', 'Conforme'), ('non_conforming', 'Não Conforme'), ('not_applicable', 'Não Aplicável')], default='pending', max_length=20, verbose_name='status')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='respondido por')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklists.checklistexecution')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='checklists.checklisttemplateitem')),
            ],
            options={
                'verbose_name': 'Item da Execução',
                'verbose_name_plural': 'Itens da Execução',
                'db_table': 'checklist_execucao_itens',
                'ordering': ['template_item__category__ordem', 'template_item__ordem'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('file', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='arquivo')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('execution_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='checklists.checklistexecutionitem')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
                'db_table': 'evidencias',
            },
        ),
    ]
