# Generated by Django 5.1.6 on 2026-03-11 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='hora início')),
                ('hora_fim', models.TimeField(verbose_name='hora fim')),
                ('categoria', models.CharField(choices=[('reuniao', 'Reunião'), ('diagnostico', 'Diagnóstico'), ('checklist', 'Checklist'), ('plano_acao', 'Plano de Ação'), ('treinamento', 'Treinamento'), ('suporte', 'Suporte / Atendimento'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], default='reuniao', max_length=20, verbose_name='categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='clientes.cliente', verbose_name='cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_horas', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'db_table': 'timesheet_registro',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
