# Generated by Django 5.1.6 on 2026-03-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('oficial_ml', 'Oficial Mercado Livre'), ('ecommerce', 'E-commerce Geral'), ('sazonal', 'Sazonal / Comemorativa'), ('custom', 'Personalizada')], max_length=20, verbose_name='tipo')),
                ('importancia', models.CharField(choices=[('critica', 'Crítica (não perder)'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=20, verbose_name='importância')),
                ('data_inicio', models.DateField(verbose_name='data início')),
                ('data_fim', models.DateField(verbose_name='data fim')),
                ('inscricao_inicio', models.DateField(blank=True, null=True, verbose_name='início inscrição')),
                ('inscricao_fim', models.DateField(blank=True, null=True, verbose_name='fim inscrição')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('dicas', models.TextField(blank=True, verbose_name='dicas para o seller')),
                ('categorias_foco', models.JSONField(blank=True, default=list, help_text='Lista de categorias que mais vendem nesta data.', verbose_name='categorias em foco')),
                ('cor', models.CharField(default='#FE8103', max_length=7, verbose_name='cor')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='ícone')),
                ('link_ml', models.URLField(blank=True, verbose_name='link ML (inscrição/info)')),
                ('antecedencia_preparo_dias', models.PositiveIntegerField(default=30, help_text='Quantos dias antes o seller deve começar a se preparar.', verbose_name='antecedência de preparo (dias)')),
            ],
            options={
                'verbose_name': 'Data Promocional',
                'verbose_name_plural': 'Datas Promocionais',
                'db_table': 'calendario_data_promocional',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PreparacaoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('status', models.CharField(choices=[('nao_participando', 'Não Participando'), ('preparando', 'Preparando'), ('inscrito', 'Inscrito'), ('pronto', 'Pronto'), ('participando', 'Participando'), ('concluido', 'Concluído')], default='nao_participando', max_length=20, verbose_name='status')),
                ('produtos_selecionados', models.JSONField(blank=True, default=list, help_text='Lista de produtos que participarão da promoção.', verbose_name='produtos selecionados')),
                ('desconto_medio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='desconto médio (%)')),
                ('budget_ads', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='budget Ads (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('resultado_vendas', models.PositiveIntegerField(default=0, verbose_name='vendas no período')),
                ('resultado_faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='faturamento (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparacoes_promocionais', to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparacoes_promo', to=settings.AUTH_USER_MODEL)),
                ('data_promocional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparacoes', to='calendario_promocional.datapromocional')),
            ],
            options={
                'verbose_name': 'Preparação Promocional',
                'verbose_name_plural': 'Preparações Promocionais',
                'db_table': 'calendario_preparacao',
                'ordering': ['-data_promocional__data_inicio'],
                'unique_together': {('data_promocional', 'cliente')},
            },
        ),
    ]
