# Generated by Django 5.1.6 on 2026-03-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('google', 'Google (Calendar)'), ('evolution', 'Evolution API (WhatsApp)'), ('brevo', 'Brevo (E-mail)'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='categoria')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='chave')),
                ('valor', models.TextField(blank=True, verbose_name='valor')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('is_secret', models.BooleanField(default=False, help_text='Valores secretos são mascarados na listagem do admin.', verbose_name='é segredo?')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'db_table': 'core_configuracao',
                'ordering': ['categoria', 'chave'],
            },
        ),
    ]
