# Generated by Django 5.1.6 on 2026-03-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_configuracao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='categoria',
            field=models.CharField(choices=[('google', 'Google (Calendar)'), ('evolution', 'Evolution API (WhatsApp)'), ('brevo', 'Brevo (E-mail)'), ('asaas', 'Asaas (Pagamentos)'), ('autentique', 'Autentique (Assinatura Digital)'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='categoria'),
        ),
    ]
