# Generated by Django 5.1.6 on 2026-03-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_funcionario'),
        ('core', '0004_alter_configuracao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='categoria',
            field=models.CharField(choices=[('uazapi', 'UAZAPI (WhatsApp)'), ('google', 'Google (Calendar)'), ('evolution', 'Evolution API (WhatsApp) — Legado'), ('brevo', 'Brevo (E-mail)'), ('asaas', 'Asaas (Pagamentos)'), ('autentique', 'Autentique (Assinatura Digital)'), ('ia', 'Inteligência Artificial'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='GrupoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('group_id', models.CharField(help_text='ID retornado pela API (ex: 5511999999999-1234567890@g.us)', max_length=100, unique=True, verbose_name='ID do grupo')),
                ('nome', models.CharField(max_length=300, verbose_name='nome do grupo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('foto_url', models.URLField(blank=True, verbose_name='foto URL')),
                ('participantes_count', models.PositiveIntegerField(default=0, verbose_name='nº participantes')),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_whatsapp', to='clientes.cliente', verbose_name='cliente vinculado')),
            ],
            options={
                'verbose_name': 'Grupo WhatsApp',
                'verbose_name_plural': 'Grupos WhatsApp',
                'db_table': 'core_grupo_whatsapp',
                'ordering': ['nome'],
            },
        ),
    ]
