# Generated by Django 5.1.6 on 2026-03-11 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracao_categoria_grupowhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupowhatsapp',
            name='ultima_interacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última interação'),
        ),
        migrations.AddField(
            model_name='grupowhatsapp',
            name='ultima_mensagem_enviada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última mensagem enviada'),
        ),
        migrations.CreateModel(
            name='MensagemGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('texto', models.TextField(verbose_name='mensagem')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('sucesso', models.BooleanField(default=True, verbose_name='enviado com sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.grupowhatsapp', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'Mensagem de Grupo',
                'verbose_name_plural': 'Mensagens de Grupo',
                'db_table': 'core_mensagem_grupo',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
