# Generated by Django 5.1.6 on 2026-03-11 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_mensagem_grupo_e_campos_interacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemgrupo',
            name='origem',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('webhook', 'WhatsApp')], default='sistema', max_length=20, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='mensagemgrupo',
            name='remetente_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome do remetente'),
        ),
        migrations.AddField(
            model_name='mensagemgrupo',
            name='remetente_telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telefone do remetente'),
        ),
        migrations.AlterField(
            model_name='mensagemgrupo',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviado por (sistema)'),
        ),
    ]
