# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('empresa', models.CharField(max_length=200, verbose_name='empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('nicho', models.CharField(blank=True, max_length=100, verbose_name='nicho')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clientes/logos/', verbose_name='logo')),
                ('ml_nickname', models.CharField(blank=True, max_length=100, verbose_name='apelido ML')),
                ('ml_seller_id', models.CharField(blank=True, max_length=50, verbose_name='seller ID ML')),
                ('ml_reputacao', models.CharField(blank=True, max_length=50, verbose_name='reputação ML')),
                ('tipo_consultoria', models.CharField(choices=[('estrategica', 'Estratégica'), ('operacional', 'Operacional')], max_length=20, verbose_name='tipo de consultoria')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('encerrado', 'Encerrado')], default='onboarding', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('consultor', models.ForeignKey(limit_choices_to={'role': 'consultor'}, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
                ('usuario', models.OneToOneField(blank=True, limit_choices_to={'role': 'seller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='acesso seller')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades',
            },
        ),
    ]
