# Generated by Django 5.1.6 on 2026-03-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('cor', models.CharField(default='#3b82f6', max_length=7, verbose_name='cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Etapa do Pipeline',
                'verbose_name_plural': 'Etapas do Pipeline',
                'db_table': 'etapas_pipeline',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.etapapipeline', verbose_name='etapa pipeline'),
        ),
    ]
