# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('plano', models.CharField(max_length=100, verbose_name='plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mensal')),
                ('dia_vencimento', models.PositiveIntegerField(default=10, verbose_name='dia do vencimento')),
                ('data_inicio', models.DateField(verbose_name='início do contrato')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim do contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('mes_referencia', models.DateField(verbose_name='mês referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.contrato')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamentos',
                'ordering': ['-mes_referencia'],
            },
        ),
    ]
