# Generated by Django 5.1.6 on 2026-03-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Customer ID'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Subscription ID'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='subscription_status',
            field=models.CharField(choices=[('nao_integrado', 'Não Integrado'), ('ativa', 'Ativa'), ('inativa', 'Inativa'), ('expirada', 'Expirada')], default='nao_integrado', max_length=20, verbose_name='status assinatura'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Payment ID'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='boleto_linha_digitavel',
            field=models.CharField(blank=True, max_length=100, verbose_name='linha digitável'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='boleto_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL do boleto'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='referência externa'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('manual', 'Manual'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito')], default='manual', max_length=20, verbose_name='método'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_code',
            field=models.TextField(blank=True, verbose_name='código PIX copia-e-cola'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_qr_code_image',
            field=models.TextField(blank=True, verbose_name='QR Code PIX (base64)'),
        ),
    ]
