# Generated by Django 5.1.6 on 2026-03-11 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_contrato_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome do template')),
                ('conteudo', models.TextField(help_text='Use variáveis: {cliente}, {empresa}, {cpf_cnpj}, {valor}, {plano}, {data_inicio}, {data_fim}, {dia_vencimento}', verbose_name='conteúdo HTML')),
            ],
            options={
                'verbose_name': 'Template de Contrato',
                'verbose_name_plural': 'Templates de Contrato',
                'db_table': 'contrato_templates',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='autentique_doc_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autentique Document ID'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pdf_arquivo',
            field=models.FileField(blank=True, upload_to='contratos/', verbose_name='PDF do contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status_assinatura',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado para assinatura'), ('assinado', 'Assinado'), ('recusado', 'Recusado')], default='rascunho', max_length=20, verbose_name='status assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contratotemplate', verbose_name='template do contrato'),
        ),
    ]
