# Generated by Django 5.1.6 on 2026-03-10 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_etapapipeline_cliente_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioAtualizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('mlb', models.CharField(max_length=30, verbose_name='MLB')),
                ('titulo', models.CharField(max_length=500, verbose_name='título')),
                ('precisa_foto', models.BooleanField(default=False, verbose_name='precisa foto')),
                ('precisa_video', models.BooleanField(default=False, verbose_name='precisa vídeo')),
                ('foto_feito', models.BooleanField(default=False, verbose_name='foto feito')),
                ('video_feito', models.BooleanField(default=False, verbose_name='vídeo feito')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_atualizar', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Anúncio para Atualizar',
                'verbose_name_plural': 'Anúncios para Atualizar',
                'db_table': 'anuncios_atualizar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadCurvaABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('periodo', models.CharField(choices=[('7d', 'Últimos 7 dias'), ('30d', 'Últimos 30 dias')], max_length=5, verbose_name='período')),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('arquivo', models.FileField(upload_to='anuncios/curva_abc/%Y/%m/', verbose_name='arquivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_curva_abc', to='clientes.cliente')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads_curva_abc', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Upload Curva ABC',
                'verbose_name_plural': 'Uploads Curva ABC',
                'db_table': 'uploads_curva_abc',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemCurvaABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('classe', models.CharField(max_length=5, verbose_name='classe')),
                ('mlb', models.CharField(max_length=30, verbose_name='MLB')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('titulo', models.CharField(max_length=500, verbose_name='título')),
                ('marca', models.CharField(blank=True, max_length=200, verbose_name='marca')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='status')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='tipo')),
                ('catalogo', models.CharField(blank=True, max_length=10, verbose_name='catálogo')),
                ('logistica', models.CharField(blank=True, max_length=50, verbose_name='logística')),
                ('estoque', models.IntegerField(default=0, verbose_name='estoque')),
                ('preco_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço atual')),
                ('quantidade', models.IntegerField(default=0, verbose_name='quantidade vendida')),
                ('ticket_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ticket médio')),
                ('faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='faturamento')),
                ('margem', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='margem')),
                ('percentual_total', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% do total')),
                ('percentual_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% acumulado')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='anuncios.uploadcurvaabc')),
            ],
            options={
                'verbose_name': 'Item Curva ABC',
                'verbose_name_plural': 'Itens Curva ABC',
                'db_table': 'itens_curva_abc',
                'ordering': ['classe', '-faturamento'],
            },
        ),
        migrations.CreateModel(
            name='UploadMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('periodo', models.CharField(choices=[('7d', 'Últimos 7 dias'), ('30d', 'Últimos 30 dias')], max_length=5, verbose_name='período')),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('arquivo', models.FileField(upload_to='anuncios/metricas/%Y/%m/', verbose_name='arquivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_metricas', to='clientes.cliente')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads_metricas', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Upload Métricas',
                'verbose_name_plural': 'Uploads Métricas',
                'db_table': 'uploads_metricas',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('mlb', models.CharField(max_length=30, verbose_name='MLB')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='status')),
                ('geral', models.IntegerField(default=0, verbose_name='geral')),
                ('vendas_30d', models.IntegerField(default=0, verbose_name='vendas 30d')),
                ('visitas', models.IntegerField(default=0, verbose_name='visitas')),
                ('conversao', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='conversão')),
                ('avaliacao', models.IntegerField(default=0, verbose_name='avaliação')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço')),
                ('categoria', models.CharField(blank=True, max_length=200, verbose_name='categoria')),
                ('video', models.CharField(blank=True, max_length=50, verbose_name='vídeo')),
                ('foto', models.CharField(blank=True, max_length=50, verbose_name='foto')),
                ('frete', models.CharField(blank=True, max_length=100, verbose_name='frete')),
                ('ads', models.CharField(blank=True, max_length=100, verbose_name='ADS')),
                ('promo', models.CharField(blank=True, max_length=100, verbose_name='promo')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='anuncios.uploadmetricas')),
            ],
            options={
                'verbose_name': 'Item Métrica',
                'verbose_name_plural': 'Itens Métricas',
                'db_table': 'itens_metricas',
                'ordering': ['-geral'],
            },
        ),
    ]
