# Generated by Django 5.1.6 on 2026-03-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('icone', models.CharField(default='clipboard', max_length=50, verbose_name='icone')),
                ('cor', models.CharField(default='#6366f1', max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'Tipo de Tarefa',
                'verbose_name_plural': 'Tipos de Tarefa',
                'db_table': 'tipos_tarefa',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.tipotarefa', verbose_name='tipo'),
        ),
    ]
