# Generated by Django 5.1.6 on 2026-03-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('tarefas', '0002_tipotarefa_tarefa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='checklist_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='checklists.checklistexecution', verbose_name='checklist vinculado'),
        ),
    ]
