# Generated by Django 5.1.6 on 2026-03-11 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_funcionario'),
        ('tarefas', '0003_add_checklist_execution_to_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cor', models.CharField(default='#6366f1', max_length=7, verbose_name='cor')),
                ('icone', models.CharField(blank=True, default='circle', max_length=50, verbose_name='ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_concluido', models.BooleanField(default=False, verbose_name='é conclusão')),
            ],
            options={
                'verbose_name': 'Etapa de Tarefa',
                'verbose_name_plural': 'Etapas de Tarefa',
                'db_table': 'etapas_tarefa',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cor', models.CharField(default='#3b82f6', max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'etiquetas_tarefa',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['ordem_kanban'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='ordem_kanban',
            field=models.PositiveIntegerField(default=0, verbose_name='ordem no kanban'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.CreateModel(
            name='AtividadeTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(max_length=30, verbose_name='tipo')),
                ('descricao', models.CharField(max_length=500, verbose_name='descrição')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_tarefa', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades_tarefa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_tarefa', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'db_table': 'comentarios_tarefa',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.etapatarefa', verbose_name='etapa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='tarefas.etiquetatarefa', verbose_name='etiquetas'),
        ),
        migrations.CreateModel(
            name='SubTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluída')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtarefas', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Subtarefa',
                'verbose_name_plural': 'Subtarefas',
                'db_table': 'subtarefas',
                'ordering': ['ordem'],
            },
        ),
    ]
