# Generated by Django 5.1.6 on 2026-03-11 23:31

from django.db import migrations


ETAPAS_PADRAO = [
    {"nome": "A Fazer", "cor": "#6366f1", "icone": "circle", "ordem": 0, "is_concluido": False},
    {"nome": "Em Andamento", "cor": "#f59e0b", "icone": "loader", "ordem": 1, "is_concluido": False},
    {"nome": "Em Revisão", "cor": "#8b5cf6", "icone": "eye", "ordem": 2, "is_concluido": False},
    {"nome": "Concluído", "cor": "#22c55e", "icone": "check-circle", "ordem": 3, "is_concluido": True},
]

STATUS_TO_ETAPA = {
    "pendente": "A Fazer",
    "em_andamento": "Em Andamento",
    "concluido": "Concluído",
    "atrasado": "A Fazer",
}


def populate_etapas(apps, schema_editor):
    EtapaTarefa = apps.get_model("tarefas", "EtapaTarefa")
    Tarefa = apps.get_model("tarefas", "Tarefa")

    # Create default stages
    etapas = {}
    for data in ETAPAS_PADRAO:
        etapa = EtapaTarefa.objects.create(**data)
        etapas[data["nome"]] = etapa

    # Migrate existing tasks: set titulo + etapa
    for tarefa in Tarefa.objects.all():
        tarefa.titulo = (tarefa.descricao or "")[:200]
        etapa_nome = STATUS_TO_ETAPA.get(tarefa.status, "A Fazer")
        tarefa.etapa = etapas.get(etapa_nome)
        tarefa.save(update_fields=["titulo", "etapa"])


def reverse_populate(apps, schema_editor):
    EtapaTarefa = apps.get_model("tarefas", "EtapaTarefa")
    EtapaTarefa.objects.filter(nome__in=[e["nome"] for e in ETAPAS_PADRAO]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0004_kanban_tarefas"),
    ]

    operations = [
        migrations.RunPython(populate_etapas, reverse_populate),
    ]
