# Generated by Django 5.1.6 on 2026-03-10 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('icone', models.CharField(default='award', max_length=50, verbose_name='icone')),
                ('tipo', models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], default='bronze', max_length=20, verbose_name='tipo')),
                ('pontos_recompensa', models.IntegerField(default=0, verbose_name='pontos recompensa')),
                ('criterio_campo', models.CharField(help_text='Ex: checklists_concluidos, tarefas_concluidas, score_diagnostico', max_length=50, verbose_name='campo criterio')),
                ('criterio_valor', models.IntegerField(help_text='Valor minimo para desbloquear', verbose_name='valor criterio')),
                ('publico', models.CharField(choices=[('consultor', 'Consultor'), ('seller', 'Seller'), ('ambos', 'Ambos')], default='ambos', max_length=20, verbose_name='publico')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'db_table': 'gamificacao_achievements',
                'ordering': ['tipo', 'criterio_valor'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('pontos', models.IntegerField(verbose_name='pontos')),
                ('categoria', models.CharField(choices=[('checklist', 'Checklist'), ('diagnostico', 'Diagnostico'), ('tarefa', 'Tarefa'), ('reuniao', 'Reuniao'), ('bonus', 'Bonus')], max_length=20, verbose_name='categoria')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID referencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'gamificacao_scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('dias_consecutivos', models.IntegerField(default=0, verbose_name='dias consecutivos')),
                ('maior_sequencia', models.IntegerField(default=0, verbose_name='maior sequencia')),
                ('ultimo_dia', models.DateField(blank=True, null=True, verbose_name='ultimo dia ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
                'db_table': 'gamificacao_streaks',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('desbloqueado_em', models.DateTimeField(auto_now_add=True, verbose_name='desbloqueado em')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueios', to='gamificacao.achievement')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuario',
                'verbose_name_plural': 'Conquistas dos Usuarios',
                'db_table': 'gamificacao_user_achievements',
                'unique_together': {('usuario', 'achievement')},
            },
        ),
    ]
