# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('categoria', models.CharField(choices=[('seo', 'SEO para Anúncios'), ('ads', 'Mercado Ads'), ('full', 'Logística FULL'), ('reputacao', 'Reputação'), ('catalogo', 'Catálogo'), ('vendas', 'Vendas'), ('outro', 'Outro')], max_length=20, verbose_name='categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('conteudo_url', models.URLField(blank=True, verbose_name='link do conteúdo')),
                ('duracao_minutos', models.PositiveIntegerField(default=0, verbose_name='duração (min)')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'db_table': 'treinamentos',
            },
        ),
        migrations.CreateModel(
            name='TreinamentoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data', models.DateField(verbose_name='data de realização')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos_realizados', to='clientes.cliente')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='treinamentos.treinamento')),
            ],
            options={
                'verbose_name': 'Treinamento Realizado',
                'verbose_name_plural': 'Treinamentos Realizados',
                'db_table': 'treinamentos_realizados',
                'unique_together': {('treinamento', 'cliente')},
            },
        ),
    ]
