# Generated by Django 5.1.6 on 2026-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='material',
            field=models.FileField(blank=True, upload_to='treinamentos/', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='treinamentorealizado',
            name='material_especifico',
            field=models.FileField(blank=True, upload_to='treinamentos/clientes/', verbose_name='material específico'),
        ),
    ]
