# Generated by Django 5.1.6 on 2026-03-11 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        ('propostas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('cor', models.CharField(default='#3b82f6', max_length=7, verbose_name='cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_ganho', models.BooleanField(default=False, verbose_name='é etapa de ganho?')),
                ('is_perdido', models.BooleanField(default=False, verbose_name='é etapa de perda?')),
            ],
            options={
                'verbose_name': 'Etapa CRM',
                'verbose_name_plural': 'Etapas CRM',
                'db_table': 'crm_etapas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome do responsável')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='empresa/loja')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('nicho', models.CharField(blank=True, max_length=100, verbose_name='nicho')),
                ('origem', models.CharField(choices=[('indicacao', 'Indicação'), ('site', 'Site'), ('redes_sociais', 'Redes Sociais'), ('evento', 'Evento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origem', to='clientes.cliente', verbose_name='cliente convertido')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'crm_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LembreteCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_hora', models.DateTimeField(verbose_name='data/hora do lembrete')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('enviado', models.BooleanField(default=False, verbose_name='enviado?')),
                ('enviar_whatsapp', models.BooleanField(default=True, verbose_name='enviar WhatsApp?')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='enviar e-mail?')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='crm.lead')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes_crm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'db_table': 'crm_lembretes',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor estimado')),
                ('previsao_fechamento', models.DateField(blank=True, null=True, verbose_name='previsão de fechamento')),
                ('motivo_perda', models.TextField(blank=True, verbose_name='motivo da perda')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.etapacrm', verbose_name='etapa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.lead')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_crm', to='propostas.proposta')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_crm', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'db_table': 'crm_oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('whatsapp', 'WhatsApp'), ('mudanca_etapa', 'Mudança de Etapa')], default='nota', max_length=20, verbose_name='tipo')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_crm', to='crm.lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_crm', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Atividade CRM',
                'verbose_name_plural': 'Atividades CRM',
                'db_table': 'crm_atividades',
                'ordering': ['-created_at'],
            },
        ),
    ]
