# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('tarefa_atrasada', 'Tarefa Atrasada'), ('inadimplencia', 'Inadimplência'), ('reuniao_marcada', 'Reunião Marcada'), ('diagnostico_pendente', 'Diagnóstico Pendente'), ('sem_reuniao', 'Sem Reunião há 30 dias'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes',
            },
        ),
    ]
