# Generated by Django 5.1.6 on 2026-03-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='enviado_email',
            field=models.BooleanField(default=False, verbose_name='enviado e-mail'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='enviado_whatsapp',
            field=models.BooleanField(default=False, verbose_name='enviado WhatsApp'),
        ),
    ]
