# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico Inicial'), ('treinamento_full', 'Treinamento FULL'), ('treinamento_reputacao', 'Treinamento Reputação'), ('treinamento_ads', 'Treinamento ADS'), ('revisao_mensal', 'Revisão Mensal'), ('outro', 'Outro')], max_length=30, verbose_name='tipo')),
                ('data', models.DateTimeField(verbose_name='data/hora')),
                ('duracao_minutos', models.PositiveIntegerField(default=60, verbose_name='duração (min)')),
                ('participantes', models.TextField(blank=True, verbose_name='participantes')),
                ('link_gravacao', models.URLField(blank=True, verbose_name='link gravação')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('proximos_passos', models.TextField(blank=True, verbose_name='próximos passos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='clientes.cliente')),
                ('consultor', models.ForeignKey(limit_choices_to={'role__in': ['consultor', 'gestor']}, on_delete=django.db.models.deletion.PROTECT, related_name='reunioes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'db_table': 'reunioes',
            },
        ),
    ]
