# Generated by Django 5.1.6 on 2026-03-11 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='consultor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['consultor', 'gestor', 'comercial']}, on_delete=django.db.models.deletion.PROTECT, related_name='reunioes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico Inicial'), ('treinamento_full', 'Treinamento FULL'), ('treinamento_reputacao', 'Treinamento Reputação'), ('treinamento_ads', 'Treinamento ADS'), ('revisao_mensal', 'Revisão Mensal'), ('comercial', 'Reunião Comercial'), ('outro', 'Outro')], max_length=30, verbose_name='tipo'),
        ),
    ]
