# Generated by Django 5.1.6 on 2026-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0002_alter_reuniao_consultor_alter_reuniao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='acoes_identificadas',
            field=models.JSONField(blank=True, default=list, verbose_name='ações identificadas'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='audio_arquivo',
            field=models.FileField(blank=True, upload_to='reunioes/audios/%Y/%m/', verbose_name='áudio da reunião'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='insights_ia',
            field=models.JSONField(blank=True, default=list, verbose_name='insights IA'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='resumo_ia',
            field=models.TextField(blank=True, verbose_name='resumo IA'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='sentimento_cliente',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo'), ('misto', 'Misto')], max_length=20, verbose_name='sentimento do cliente'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='transcricao',
            field=models.TextField(blank=True, help_text='Transcrição precisa gerada pelo Whisper', verbose_name='transcrição final'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='transcricao_rascunho',
            field=models.TextField(blank=True, help_text='Transcrição gerada em tempo real pelo navegador', verbose_name='transcrição ao vivo'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='transcricao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='status transcrição'),
        ),
    ]
