# Generated by Django 5.1.6 on 2026-03-10 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_etapapipeline_cliente_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Classe CSS do ícone', max_length=50, verbose_name='ícone')),
                ('preco_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço sugerido')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'propostas_servicos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('lead_nome', models.CharField(blank=True, max_length=200, verbose_name='nome do responsável')),
                ('lead_loja', models.CharField(blank=True, max_length=200, verbose_name='nome da loja')),
                ('lead_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('lead_telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('tipo_seller', models.CharField(choices=[('iniciante', 'Iniciante'), ('estruturando', 'Estruturando'), ('escalando', 'Escalando'), ('avancado', 'Operação Avançada'), ('industria', 'Indústria'), ('distribuidor', 'Distribuidor')], max_length=20, verbose_name='tipo de seller')),
                ('marketplace', models.CharField(choices=[('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('multicanal', 'Multicanal')], default='mercado_livre', max_length=20, verbose_name='marketplace principal')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('questionario', 'Questionário'), ('calculando', 'Calculando'), ('gerando_ia', 'Gerando IA'), ('revisao', 'Em Revisão'), ('enviado', 'Enviado'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('expirado', 'Expirado')], default='rascunho', max_length=20, verbose_name='status')),
                ('passo_atual', models.PositiveIntegerField(default=1, verbose_name='passo atual')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token público')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='data de expiração')),
                ('respostas', models.JSONField(default=dict, verbose_name='respostas')),
                ('metricas', models.JSONField(default=dict, verbose_name='métricas')),
                ('diagnostico_ia', models.TextField(blank=True, verbose_name='diagnóstico IA')),
                ('proposicao_valor', models.TextField(blank=True, verbose_name='proposição de valor')),
                ('proposta_comercial', models.TextField(blank=True, verbose_name='proposta comercial')),
                ('valor_setup', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de setup')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='mensalidade')),
                ('condicoes_especiais', models.TextField(blank=True, verbose_name='condições especiais')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='visualizações')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='data de envio')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='data da resposta')),
                ('motivo_recusa', models.TextField(blank=True, verbose_name='motivo da recusa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='clientes.cliente', verbose_name='cliente existente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropostaVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_visualizacoes', to='propostas.proposta')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'db_table': 'propostas_visualizacoes',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PropostaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('descricao_custom', models.TextField(blank=True, verbose_name='descrição customizada')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_incluidos', to='propostas.proposta')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_servico', to='propostas.servico')),
            ],
            options={
                'verbose_name': 'Serviço da Proposta',
                'verbose_name_plural': 'Serviços da Proposta',
                'db_table': 'propostas_servicos_incluidos',
                'ordering': ['ordem'],
            },
        ),
    ]
