# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_templates', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Template de Diagnóstico',
                'verbose_name_plural': 'Templates de Diagnóstico',
                'db_table': 'diagnostic_templates',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('categoria', models.CharField(help_text='Ex: Vendas, Logística, Reputação', max_length=100, verbose_name='categoria')),
                ('texto', models.CharField(max_length=500, verbose_name='pergunta')),
                ('tipo', models.CharField(choices=[('scale_1_10', 'Escala 1 a 10'), ('value', 'Valor Numérico'), ('selection', 'Seleção')], max_length=20, verbose_name='tipo')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso na média ponderada', max_digits=5, verbose_name='peso')),
                ('is_inverted', models.BooleanField(default=False, help_text='Marque se menor valor = melhor resultado', verbose_name='invertida')),
                ('options', models.JSONField(blank=True, help_text='Para tipo "selection": {"Bom": 8, "Regular": 5, "Ruim": 2}', null=True, verbose_name='opções')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='diagnosticos.diagnostictemplate')),
            ],
            options={
                'verbose_name': 'Pergunta do Diagnóstico',
                'verbose_name_plural': 'Perguntas do Diagnóstico',
                'db_table': 'diagnostic_questions',
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mês')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('scores_por_categoria', models.JSONField(blank=True, default=dict, help_text='Ex: {"Vendas": 7.2, "Logística": 5.8}', verbose_name='scores por categoria')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='clientes.cliente')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_executados', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='diagnosticos.diagnostictemplate')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnosticos',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cliente', 'mes', 'ano', 'template')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor numérico')),
                ('value_text', models.CharField(blank=True, max_length=200, verbose_name='valor texto')),
                ('score', models.DecimalField(decimal_places=1, default=0, help_text='Score normalizado 0-10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='diagnosticos.diagnostic')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='diagnosticos.diagnosticquestion')),
            ],
            options={
                'verbose_name': 'Resposta do Diagnóstico',
                'verbose_name_plural': 'Respostas do Diagnóstico',
                'db_table': 'diagnostic_answers',
                'unique_together': {('diagnostic', 'question')},
            },
        ),
    ]
