# Generated by Django 5.1.6 on 2026-03-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('segmento', models.CharField(max_length=100, unique=True, verbose_name='segmento')),
                ('score_medio', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='score médio')),
                ('scores_por_categoria', models.JSONField(blank=True, default=dict, verbose_name='scores por categoria')),
                ('total_diagnosticos', models.PositiveIntegerField(default=0, verbose_name='total diagnósticos')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Benchmark por Segmento',
                'verbose_name_plural': 'Benchmarks por Segmento',
                'db_table': 'benchmark_segmentos',
                'ordering': ['segmento'],
            },
        ),
    ]
