# Generated by Django 5.1.6 on 2026-03-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('clientes', '0003_funcionario'),
        ('diagnosticos', '0002_benchmarksegmento'),
        ('reunioes', '0003_reuniao_acoes_identificadas_reuniao_audio_arquivo_and_more'),
        ('tarefas', '0003_add_checklist_execution_to_tarefa'),
        ('treinamentos', '0002_treinamento_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo_consultoria', models.CharField(blank=True, help_text='Deixe vazio para aplicar a qualquer tipo', max_length=20, verbose_name='tipo de consultoria')),
                ('icone', models.CharField(blank=True, default='map', max_length=50, verbose_name='ícone')),
                ('cor', models.CharField(default='#FE8103', max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'Template de Jornada',
                'verbose_name_plural': 'Templates de Jornada',
                'db_table': 'jornada_templates',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('diagnostico', 'Diagnóstico'), ('checklist', 'Checklist'), ('treinamento', 'Treinamento'), ('tarefa', 'Tarefa'), ('marco', 'Marco')], max_length=20, verbose_name='tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('dias_offset', models.PositiveIntegerField(default=0, help_text='Dias após o início da jornada para esta etapa', verbose_name='dias após início')),
                ('duracao_dias', models.PositiveIntegerField(default=7, help_text='Prazo em dias para completar esta etapa', verbose_name='prazo (dias)')),
                ('is_obrigatoria', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('condicao', models.TextField(blank=True, help_text="Regra para IA: ex: 'só se score_reputacao < 6'", verbose_name='condição IA')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checklists.checklisttemplate', verbose_name='checklist vinculado')),
                ('diagnostico_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diagnosticos.diagnostictemplate', verbose_name='diagnóstico vinculado')),
                ('treinamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treinamentos.treinamento', verbose_name='treinamento vinculado')),
                ('jornada_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='jornadas.jornadatemplate')),
            ],
            options={
                'verbose_name': 'Etapa do Template',
                'verbose_name_plural': 'Etapas do Template',
                'db_table': 'jornada_etapa_templates',
                'ordering': ['ordem', 'dias_offset'],
            },
        ),
        migrations.CreateModel(
            name='JornadaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome da jornada')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='status')),
                ('progresso', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='progresso (%)')),
                ('justificativa_ia', models.TextField(blank=True, help_text='Por que a IA recomendou esta jornada', verbose_name='justificativa da IA')),
                ('areas_foco', models.JSONField(blank=True, default=list, help_text='Categorias prioritárias identificadas pela IA', verbose_name='áreas de foco')),
                ('recalibragens', models.PositiveIntegerField(default=0, verbose_name='recalibrações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='clientes.cliente')),
                ('jornada_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='jornadas.jornadatemplate', verbose_name='template base')),
            ],
            options={
                'verbose_name': 'Jornada do Cliente',
                'verbose_name_plural': 'Jornadas dos Clientes',
                'db_table': 'jornada_clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtapaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('diagnostico', 'Diagnóstico'), ('checklist', 'Checklist'), ('treinamento', 'Treinamento'), ('tarefa', 'Tarefa'), ('marco', 'Marco')], max_length=20, verbose_name='tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('data_prevista', models.DateField(verbose_name='data prevista')),
                ('data_limite', models.DateField(verbose_name='data limite')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada'), ('pulada', 'Pulada')], default='pendente', max_length=20, verbose_name='status')),
                ('adicionada_por_ia', models.BooleanField(default=False, verbose_name='adicionada pela IA')),
                ('motivo_ia', models.TextField(blank=True, help_text='Por que a IA adicionou/recomendou esta etapa', verbose_name='motivo IA')),
                ('checklist_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_jornada', to='checklists.checklistexecution')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_jornada', to='diagnosticos.diagnostic')),
                ('reuniao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_jornada', to='reunioes.reuniao')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_jornada', to='tarefas.tarefa')),
                ('treinamento_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_jornada', to='treinamentos.treinamentorealizado')),
                ('etapa_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='jornadas.etapatemplate')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='jornadas.jornadacliente')),
            ],
            options={
                'verbose_name': 'Etapa do Cliente',
                'verbose_name_plural': 'Etapas dos Clientes',
                'db_table': 'jornada_etapa_clientes',
                'ordering': ['ordem', 'data_prevista'],
            },
        ),
    ]
