# Generated by Django 5.1.6 on 2026-03-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('tipo', models.CharField(choices=[('estrategico', 'Estratégico'), ('semanal', 'Semanal'), ('diario', 'Diário')], max_length=20, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'db_table': 'planos_acao',
            },
        ),
        migrations.CreateModel(
            name='ItemPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='prioridade')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='status')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planos.planoacao')),
            ],
            options={
                'verbose_name': 'Item do Plano',
                'verbose_name_plural': 'Itens do Plano',
                'db_table': 'itens_plano',
                'ordering': ['prioridade', 'prazo'],
            },
        ),
    ]
