# Generated by Django 5.1.6 on 2026-03-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('jornada', 'Geração de Jornada'), ('recalibracao', 'Recalibração de Jornada'), ('reuniao', 'Análise de Reunião'), ('insight', 'Geração de Insights'), ('diagnostico', 'Análise de Diagnóstico')], max_length=30, verbose_name='tipo')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='provider')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('prompt_resumo', models.TextField(blank=True, verbose_name='resumo do prompt')),
                ('resposta_resumo', models.TextField(blank=True, verbose_name='resumo da resposta')),
                ('resposta_json', models.JSONField(blank=True, default=dict, verbose_name='resposta completa')),
                ('tokens_input', models.PositiveIntegerField(default=0, verbose_name='tokens input')),
                ('tokens_output', models.PositiveIntegerField(default=0, verbose_name='tokens output')),
                ('custo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='custo estimado (USD)')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='duração (ms)')),
                ('sucesso', models.BooleanField(default=True, verbose_name='sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='clientes.cliente')),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Análise IA',
                'verbose_name_plural': 'Histórico de Análises IA',
                'db_table': 'ia_historico_analises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio'), ('risco', 'Risco')], max_length=20, verbose_name='tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='prioridade')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('acao_sugerida', models.CharField(blank=True, max_length=300, verbose_name='ação sugerida')),
                ('url_acao', models.CharField(blank=True, max_length=500, verbose_name='URL da ação')),
                ('lido', models.BooleanField(default=False, verbose_name='lido')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='expira em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights_ia', to='clientes.cliente', verbose_name='cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_ia', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
            ],
            options={
                'verbose_name': 'Insight IA',
                'verbose_name_plural': 'Insights IA',
                'db_table': 'ia_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
