# Generated by Django 5.1.6 on 2026-03-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_etapapipeline_cliente_etapa'),
        ('reunioes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseSwot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('forcas', models.JSONField(default=list, verbose_name='forças')),
                ('fraquezas', models.JSONField(default=list, verbose_name='fraquezas')),
                ('oportunidades', models.JSONField(default=list, verbose_name='oportunidades')),
                ('ameacas', models.JSONField(default=list, verbose_name='ameaças')),
                ('segmento_mercado', models.CharField(blank=True, max_length=200, verbose_name='segmento de mercado')),
                ('publico_alvo', models.CharField(blank=True, max_length=300, verbose_name='público-alvo')),
                ('concorrentes', models.TextField(blank=True, verbose_name='principais concorrentes')),
                ('diferencial', models.TextField(blank=True, verbose_name='diferencial competitivo')),
                ('observacoes_mercado', models.TextField(blank=True, verbose_name='observações do mercado')),
                ('produtos_principais', models.JSONField(default=list, verbose_name='produtos principais')),
                ('data_analise', models.DateField(verbose_name='data da análise')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_swot', to='clientes.cliente', verbose_name='cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_swot', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
                ('reuniao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_swot', to='reunioes.reuniao', verbose_name='reunião vinculada')),
            ],
            options={
                'verbose_name': 'Análise SWOT',
                'verbose_name_plural': 'Análises SWOT',
                'db_table': 'analises_swot',
                'ordering': ['-data_analise'],
            },
        ),
    ]
