# Generated by Django 5.1.6 on 2026-03-11 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_hora', models.DateTimeField(verbose_name='data/hora')),
                ('duracao', models.PositiveIntegerField(default=60, verbose_name='duração (min)')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='nome')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone_cliente', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('google_event_id', models.CharField(blank=True, max_length=300, verbose_name='ID evento Google')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado'), ('nao_compareceu', 'Não Compareceu')], default='confirmado', max_length=20, verbose_name='status')),
                ('token_cancelamento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token cancelamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clientes.cliente')),
                ('consultor', models.ForeignKey(limit_choices_to={'role__in': ['consultor', 'gestor']}, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agenda_agendamentos',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug público')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título da agenda')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('duracao_padrao', models.PositiveIntegerField(default=60, verbose_name='duração padrão (min)')),
                ('antecedencia_minima', models.PositiveIntegerField(default=24, verbose_name='antecedência mínima (horas)')),
                ('dias_visiveis', models.PositiveIntegerField(default=14, verbose_name='dias visíveis')),
                ('google_token', models.JSONField(blank=True, null=True, verbose_name='token Google')),
                ('google_calendar_id', models.CharField(blank=True, max_length=300, verbose_name='ID do calendário Google')),
                ('consultor', models.OneToOneField(limit_choices_to={'role__in': ['consultor', 'gestor']}, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Agenda',
                'verbose_name_plural': 'Configurações de Agenda',
                'db_table': 'agenda_configuracoes',
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora início')),
                ('hora_fim', models.TimeField(verbose_name='hora fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.configuracaoagenda')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'db_table': 'agenda_horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('config', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
