# Generated by Django 5.1.6 on 2026-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='confirmado_pelo_cliente',
            field=models.BooleanField(default=False, verbose_name='confirmado pelo cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado',
            field=models.BooleanField(default=False, verbose_name='lembrete enviado'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='mensagem_enviada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mensagem enviada em'),
        ),
    ]
