# Generated by Django 5.1.6 on 2026-03-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_add_confirmacao_lembrete_campos'),
        ('core', '0007_add_mensagem_grupo_webhook_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoagenda',
            name='grupo_notificacao',
            field=models.ForeignKey(blank=True, help_text='Grupo que receberá aviso quando um novo agendamento for feito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_notificacao', to='core.grupowhatsapp', verbose_name='grupo WhatsApp para notificações'),
        ),
    ]
