# Generated by Django 5.1.6 on 2026-03-11 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_nps', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Pesquisa NPS',
                'verbose_name_plural': 'Pesquisas NPS',
                'db_table': 'nps_pesquisas',
            },
        ),
        migrations.CreateModel(
            name='RespostaNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nota', models.PositiveIntegerField(help_text='0 = Não recomendaria, 10 = Recomendaria com certeza', verbose_name='nota (0-10)')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_nps', to='clientes.cliente')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='nps.pesquisanps')),
            ],
            options={
                'verbose_name': 'Resposta NPS',
                'verbose_name_plural': 'Respostas NPS',
                'db_table': 'nps_respostas',
                'unique_together': {('pesquisa', 'cliente')},
            },
        ),
    ]
